# Generated by Django 4.1.4 on 2022-12-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_heashtec_product_heashtegs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=170)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='heashtegs',
        ),
        migrations.DeleteModel(
            name='Heashtec',
        ),
    ]
